version: '3.4'

services:
  banklyapi:
    image: node:lts-alpine
    working_dir: /usr/src/app
    command: sh -c "npm i && npm run dev"
    tty: true
    container_name: nodejs
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
    depends_on:
      - redis
      - db
    networks:
      - node-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/cache
    #command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - node-network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=db
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
    networks:
      - node-network

networks:
  node-network: