version: '3.4'

services:
  banklyapi:
    image: node:lts-alpine
    working_dir: /usr/src/app
    command: sh -c "npm i && npm run dev"
    tty: true
    container_name: nodejs
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 3333
    ports:
      - 3333:3333
    depends_on:
      - redis
      - db
    networks:
      - node-network

  db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=animes
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db:delegated
    networks:
      - node-network

networks:
  node-network: